In [1]:
# load dependencies
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect,join
import numpy as np
import pandas as pd

def SQL_Pull(budget):
    engine= create_engine("postgres://wtzcxlhtevtgnn:a611ddfea80402e93d32df58dad93c3dfe320544d635b77e14e9bb8936eeca9e@ec2-52-86-116-94.compute-1.amazonaws.com:5432/d5hl5ab4698nnc")
    Base= automap_base()
    Base.prepare(engine, reflect=True)
    
    appraisal=Base.classes.appraisal
    properties=Base.classes.properties
    crime=Base.classes.crime
    zip_code=Base.classes.zip_code
    flood_zone=Base.classes.flood_zone
    neighborhoods=Base.classes.neighborhoods
    # property_school=Base.classes.property_school
    school_district=Base.classes.school_district
    school=Base.classes.school
    session=Session(bind=engine)
    
    sel=[appraisal.id,appraisal.account,appraisal.land_value,appraisal.total_appraised_value,appraisal.total_market_value,appraisal.tax_year,\
      properties.latitude, properties.longitude, properties.Zip_code, properties.neighborhood_code,properties.acreage,\
      properties.new_owner_date, properties.sq_ft, properties.flood_description,\
      neighborhoods.neighborhood]

    appraisal_df=session.query(*sel).\
            select_from(join(join(appraisal, properties, appraisal.account==properties.account),neighborhoods,\
                           properties.neighborhood_code== neighborhoods.neighborhood_code)).\
            filter(appraisal.total_appraised_value<=budget).\
            filter(properties.sq_ft<9000).\
            all()

    appraisal_df=pd.DataFrame(appraisal_df)
    
     # Calculate % of change of value between 2018 and 2019
    appraisal_2018=appraisal_df.loc[appraisal_df.tax_year==2018,:]
    appraisal_2019=appraisal_df.loc[appraisal_df.tax_year==2019,:]
    appraisal_df=pd.merge(appraisal_2019,appraisal_2018,on='account', suffixes=('_2019','_2018'))
    appraisal_df['pct_value_change']=(appraisal_df['total_appraised_value_2019']-appraisal_df['total_appraised_value_2018'])\
                                  /appraisal_df['total_appraised_value_2018']*100
    results_df=appraisal_df[['id_2019','account','total_appraised_value_2019', 'pct_value_change','latitude_2019',\
                            'longitude_2019','acreage_2019','Zip_code_2019','neighborhood_code_2019','sq_ft_2019','neighborhood_2019', 'new_owner_date_2019',\
                             'flood_description_2019']]
    results_df=results_df.rename(columns={'id_2019':'id', 'latitude_2019':'latitude','longitude_2019':'longitude',\
                                     'Zip_code_2019':'zip_code','neighborhood_code_2019':'neighborhood_code',\
                                      'sq_ft_2019':'sq_ft','neighborhood_2019':'neighborhood','acreage_2019':'acreage',\
                                       'flood_description_2019':'flood_description','new_owner_date_2019':'new_owner_date'})
    sel=[crime.Zip_Code, func.count(crime.Offense_Count)]
    crime_df=session.query(*sel).select_from(crime).group_by(crime.Zip_Code).all()
    # crime_df=pd.DataFrame(crime_df)
    crime_df=pd.DataFrame(crime_df,columns=['zip_code','Offense_Count'])
    crime_df.head()
    results_df=pd.merge(results_df,crime_df,on="zip_code")
    
    #Read property_school table and merge to results
    property_school_df=pd.read_sql_table('property_school',engine)
    results_df=pd.merge(results_df,property_school_df,on="account")

    #Read school table and merge to results
    school_df=pd.read_sql_table('school',engine)
    results_df=pd.merge(results_df,school_df,on=['school_id','school_type'])

    #Add flood ranking#3- High Risk
    #2 - Medium Risk
    #1- Low Risk
    results_df['flood_risk']=np.where(results_df['flood_description']=='AREA OF MINIMAL FLOOD HAZARD',1,3)
    results_df.loc[(results_df['flood_description']=='0.2 PCT ANNUAL CHANCE FLOOD HAZARD'),'flood_risk']=2
    results_df.loc[(results_df['flood_description']=='FLOODWAY'),'flood_risk']=3
    del results_df['name']
    del results_df['address']
    del results_df['city']
    del results_df['zip_code_y']
    del results_df['district_id']
    del results_df['latitude_y']
    del results_df['longitude_y']
    del results_df['flood_description']
    results_df=results_df.rename(columns={'latitude_x':'latitude', 'longitude_x':'longitude', 'zip_code_x':'zip_code'})
    
    #Count the house sale per neighborhood in 2019 and merge results
    results_df=results_df.loc[results_df['account']!=530420000012,:]
    results_df['new_owner_date']=pd.to_datetime(results_df['new_owner_date'])
    results_df['sales2019']=np.where(results_df['new_owner_date']>'2018-12-31',1,0)
    sales=results_df.groupby('neighborhood_code')['sales2019'].sum()
    sales=pd.DataFrame(sales)
    sales=sales.rename(columns={'sales2019':'sales_neighborhood_2019'})
    results_df=pd.merge(results_df,sales, on="neighborhood_code")
    del results_df['sales2019']
    
    results_df['total_appraised_value_2019']=results_df['total_appraised_value_2019'].astype(float)
    results_df['pct_value_change']=results_df['pct_value_change'].astype(float)
    results_df['latitude']=results_df['latitude'].astype(float)
    results_df['longitude']=results_df['longitude'].astype(float)
    results_df['acreage']=results_df['acreage'].astype(float)
    results_df['neighborhood_code']=results_df['neighborhood_code'].astype(float)
    results_df['sq_ft']=results_df['sq_ft'].astype(float)
    
    print('data pull complete')
    return (results_df)

In [11]:
def scores (dictionaryOfUserInput):        

    w_budget = dictionaryOfUserInput["budget"]
    w_sales = dictionaryOfUserInput["salesWeight"]
    w_crime = dictionaryOfUserInput["crimeWeight"]
    w_schools = dictionaryOfUserInput["schoolWeight"]
    w_acreage = dictionaryOfUserInput["acreageWeight"]
    w_SQ_FT = dictionaryOfUserInput["sqftWeight"]
    w_flood = dictionaryOfUserInput["floodWeight"]
    w_change = dictionaryOfUserInput["changeValueWeight"]

    # call SQL_Pull function to query the database and create a dataframe
    df = SQL_Pull(w_budget)

    # Normalize data for each parameter
    max=df['sales_neighborhood_2019'].max()
    min=df['sales_neighborhood_2019'].min()
    df["Sales Index"]=(df['sales_neighborhood_2019']-min)/(max-min)*100

    max=df['Offense_Count'].max()
    min=df['Offense_Count'].min()
    df["Crime Index"]=(df['Offense_Count']-min)/(max-min)*100

    max=df['school_rating'].max()
    min=df['school_rating'].min()
    df["School Rating Index"]=(df['school_rating']-min)/(max-min)*100

    max=df['acreage'].max()
    min=df['acreage'].min()
    df["Acreage Index"]=(df['acreage']-min)/(max-min)*100

    max=df['sq_ft'].max()
    min=df['sq_ft'].min()
    df["SQ_FT Index"]=(df['sq_ft']-min)/(max-min)*100

    max=df['flood_risk'].max()
    min=df['flood_risk'].min()
    df["Flood Risk Index"]=(df['flood_risk']-min)/(max-min)*100

    max=df['pct_value_change'].max()
    df['Valuation Index']=df['pct_value_change']/max*100

    # Calculate scores for each address.
    total_weights=w_sales+w_crime+w_schools+w_acreage+w_SQ_FT+w_flood+w_change

    # Add calculated scores to the dataframe
    df["Sales Index_W"]=w_sales*df['Sales Index']
    df['Crime Index_W']= w_crime*df['Crime Index']
    df["School Rating Index_W"]=w_schools*df['School Rating Index']
    df["Acreage Index_W"]= w_acreage*df['Acreage Index']
    df["SQ_FT_Index_W"]= w_SQ_FT*df['SQ_FT Index']
    df["Flood Risk Index_W"]=w_flood*df['Flood Risk Index']
    df['Valuation Index_W']= w_change*df['Valuation Index']

    # Calculate total score per row
    df["Score"]=round((w_sales*df['Sales Index']-
                                    w_crime*df['Crime Index']+
                                    w_schools*df['School Rating Index']+
                                    w_acreage*df['Acreage Index']+
                                    w_SQ_FT*df['SQ_FT Index']-
                                    w_flood*df['Flood Risk Index']+
                                    w_change*df['Valuation Index'])/total_weights,2)

    # look at only the parameters of interest
    parameter_and_score = df[['latitude','longitude','Sales Index','Crime Index', 'School Rating Index',
            'Acreage Index','SQ_FT Index', 'Flood Risk Index', 'Valuation Index','Score',
            'total_appraised_value_2019','neighborhood']]

    # group parameters by neighborhood name
    neighborhood_group = parameter_and_score.groupby(['neighborhood']).mean()
    
    # add count of residences per neighborhood
    residence_count = parameter_and_score.groupby(["neighborhood"]).count()
    renamed_count = residence_count.rename(columns = {"latitude":"Counts"})
    single_column_counts = renamed_count["Counts"]

    # merge the counts to the neighborhood group
    neighborhood_group_with_counts = neighborhood_group.merge(single_column_counts,how='inner',on='neighborhood')

    # To get to the top list, neighborhoods need positive valuation index and non-zero sales index
    neighborhood_group_with_counts=neighborhood_group_with_counts.loc[(neighborhood_group_with_counts['Valuation Index']>0)&(neighborhood_group_with_counts['Sales Index']>0)&(neighborhood_group_with_counts['Score']>0),:]

    min=neighborhood_group_with_counts['Valuation Index'].min()
    max=neighborhood_group_with_counts['Valuation Index'].max()
    neighborhood_group_with_counts['Valuation Index']=(neighborhood_group_with_counts['Valuation Index']-min)/(max-min)*100

    min=neighborhood_group_with_counts['Score'].min()
    max=neighborhood_group_with_counts['Score'].max()
    neighborhood_group_with_counts['Score']=(neighborhood_group_with_counts['Score']-min)/(max-min)*100                                                                                                                        

    min=neighborhood_group_with_counts['Sales Index'].min()
    max=neighborhood_group_with_counts['Sales Index'].max()
    neighborhood_group_with_counts['Sales Index']=(neighborhood_group_with_counts['Sales Index']-min)/(max-min)*100 

    min=neighborhood_group_with_counts['Crime Index'].min()
    max=neighborhood_group_with_counts['Crime Index'].max()
    neighborhood_group_with_counts['Crime Index']=(neighborhood_group_with_counts['Crime Index']-min)/(max-min)*100   

    min=neighborhood_group_with_counts['School Rating Index'].min()
    max=neighborhood_group_with_counts['School Rating Index'].max()
    neighborhood_group_with_counts['School Rating Index']=(neighborhood_group_with_counts['School Rating Index']-min)/(max-min)*100

    min=neighborhood_group_with_counts['Acreage Index'].min()
    max=neighborhood_group_with_counts['Acreage Index'].max()
    neighborhood_group_with_counts['Acreage Index']=(neighborhood_group_with_counts['Acreage Index']-min)/(max-min)*100 

    min=neighborhood_group_with_counts['SQ_FT Index'].min()
    max=neighborhood_group_with_counts['SQ_FT Index'].max()
    neighborhood_group_with_counts['SQ_FT Index']=(neighborhood_group_with_counts['SQ_FT Index']-min)/(max-min)*100                                                                                                                          

    min=neighborhood_group_with_counts['Flood Risk Index'].min()
    max=neighborhood_group_with_counts['Flood Risk Index'].max()
    neighborhood_group_with_counts['Flood Risk Index']=(neighborhood_group_with_counts['Flood Risk Index']-min)/(max-min)*100   

    neighborhood_group_with_counts=neighborhood_group_with_counts.rename(columns={"total_appraised_value_2019":"Mean Value 2019"})                                                                                                                  

    # sort scores
    ranked_neighborhoods = neighborhood_group_with_counts.sort_values('Score',ascending=False)
    top5neighborhoods= ranked_neighborhoods.head()
    
    return top5neighborhoods

In [12]:
dictionaryOfUserInputs = {
    'budget': 400000,
    'salesWeight': 5,
    'crimeWeight': 5,
    'schoolWeight': 5,
    'acreageWeight': 5,
    'sqftWeight': 5,
    'floodWeight': 5,
    'changeValueWeight': 5
}

In [13]:
df = scores(dictionaryOfUserInputs)
df.head()

data pull complete

,latitude,longitude,Sales Index,Crime Index,School Rating Index,Acreage Index,SQ_FT Index,Flood Risk Index,Valuation Index,Score,Mean Value 2019,Counts
neighborhood,,,,,,,,,,,,
BUCKNER STREET T/H'S,29.756081,-95.380448,1.000000e+02,1.958580e+01,30.757309,16.976994,64.916073,0.974026,6.636569,100.000000,320382.597403,924
"WESTWOOD #2, PT 1",29.669224,-95.442947,5.600000e+01,1.402367e+01,51.339215,76.995305,29.243823,0.000000,0.423948,88.466070,203154.858369,1398
AFTON OAKS (S. OF RICHMOND),29.731951,-95.453746,9.237056e-16,3.112303e-14,83.744856,86.347665,60.022828,0.000000,11.003733,79.211504,332619.000000,45
HYDE PARK MAIN 6-ROW T/H,29.744929,-95.406500,4.000000e+01,1.512032e+01,45.165981,16.527598,55.599467,0.000000,7.649243,69.165269,334950.080000,450
WEST LANE ANNEX,29.733412,-95.449943,5.080381e-15,0.000000e+00,87.808642,57.386090,17.477529,0.000000,35.099515,67.081943,367245.750000,12